# Generated by Django 5.1.4 on 2025-01-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('thumbnail', models.URLField()),
                ('preview_link', models.URLField()),
                ('raw_price', models.IntegerField()),
                ('formatted_price', models.CharField(max_length=50)),
                ('is_successful', models.BooleanField(default=False)),
                ('order_code', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
